# Generated by Django 4.2.20 on 2025-04-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name'], 'verbose_name': 'مقصد', 'verbose_name_plural': 'مقصدها'},
        ),
        migrations.AlterField(
            model_name='destination',
            name='attractions',
            field=models.TextField(blank=True, help_text='جاذبه\u200cها را با کاما از هم جدا کنید', verbose_name='جاذبه\u200cها'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='climate',
            field=models.TextField(verbose_name='آب و هوا'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(max_length=100, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='destinations/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('city', 'شهر'), ('region', 'منطقه')], max_length=20, verbose_name='نوع مقصد'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
