# Generated by Django 4.2.20 on 2025-04-07 11:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_options_and_more'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at'], 'verbose_name': 'تور', 'verbose_name_plural': 'تورها'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'verbose_name': 'تصویر تور', 'verbose_name_plural': 'تصاویر تور'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination', verbose_name='مقصد'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.PositiveIntegerField(help_text='مدت زمان به روز', verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='excluded_services',
            field=models.TextField(blank=True, verbose_name='خدمات شامل نشده'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='included_services',
            field=models.TextField(blank=True, verbose_name='خدمات شامل شده'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary',
            field=models.TextField(blank=True, verbose_name='برنامه سفر'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='season',
            field=models.CharField(choices=[('summer', 'تابستان'), ('winter', 'زمستان'), ('spring', 'بهار'), ('autumn', 'پاییز'), ('all', 'همه فصل\u200cها')], max_length=20, verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('adventure', 'ماجراجویی'), ('cultural', 'فرهنگی'), ('beach', 'ساحلی'), ('wildlife', 'طبیعت وحش'), ('religious', 'مذهبی')], max_length=20, verbose_name='نوع تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='توضیح تصویر'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='tour_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour', verbose_name='تور'),
        ),
    ]
