# Generated by Django 4.2.20 on 2025-04-07 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_options_and_more'),
        ('tours', '0002_alter_tour_options_alter_tourimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام هتل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='درجه هتل')),
                ('amenities', models.TextField(blank=True, verbose_name='امکانات')),
                ('image', models.ImageField(blank=True, upload_to='hotel_images/', verbose_name='تصویر')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت هر شب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='destinations.destination', verbose_name='مقصد')),
            ],
            options={
                'verbose_name': 'هتل',
                'verbose_name_plural': 'هتل\u200cها',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.hotel', verbose_name='هتل\u200cهای پیشنهادی'),
        ),
    ]
