# Generated by Django 4.2.10 on 2025-04-08 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_options_and_more'),
        ('tours', '0003_hotel_tour_hotels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-rating'], 'verbose_name': 'هتل', 'verbose_name_plural': 'هتل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ['created_at'], 'verbose_name': 'تصویر تور', 'verbose_name_plural': 'تصاویر تور'},
        ),
        migrations.AddField(
            model_name='tourimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=500, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.TextField(default='[]', verbose_name='امکانات'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='درجه هتل'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='destinations.destination', verbose_name='مقصد'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(help_text='Duration in days', verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='excluded_services',
            field=models.TextField(default='[]', verbose_name='خدمات شامل نشده'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotels',
            field=models.ManyToManyField(related_name='tours', to='tours.hotel', verbose_name='هتل\u200cهای پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='included_services',
            field=models.TextField(default='[]', verbose_name='خدمات شامل شده'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Seasons')], max_length=10, verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('cultural', 'Cultural'), ('adventure', 'Adventure'), ('nature', 'Nature'), ('historical', 'Historical'), ('beach', 'Beach'), ('luxury', 'Luxury')], max_length=20, verbose_name='نوع تور'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='tours/', verbose_name='تصویر'),
        ),
    ]
