# Generated by Django 4.2.10 on 2025-04-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_hotel_options_alter_tourimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.TextField(default='[]', verbose_name='امکانات'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='excluded_services',
            field=models.TextField(default='[]', verbose_name='خدمات شامل نشده'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='included_services',
            field=models.TextField(default='[]', verbose_name='خدمات شامل شده'),
        ),
    ]
