# Generated by Django 4.2.10 on 2025-04-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_hotel_amenities_alter_tour_excluded_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان تور'),
        ),
    ]
